# Generated by Django 4.1.5 on 2023-02-04 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('category', models.CharField(choices=[('FAM', 'FAMILY'), ('EJE', 'EJECUTIVO'), ('GRA', 'GRANDS')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('payment_status', models.CharField(choices=[('COM', 'PAYMENT_COMPLETE'), ('INC', 'PAYMENT_INCOMPLETE'), ('PAR', 'PAYMENT_PARTIALLY_COMPLETE')], default='', max_length=3)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.room')),
            ],
        ),
    ]
