# Generated by Django 4.1.5 on 2023-02-23 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='payment_status',
        ),
        migrations.AddField(
            model_name='booking',
            name='estado_de_pago',
            field=models.CharField(choices=[('COM', 'COMPLETO'), ('INC', 'INCOMPLETO'), ('PAR', 'PARCIAL')], default='', max_length=3),
        ),
    ]
