# Generated by Django 4.1.5 on 2023-03-06 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_remove_booking_payment_status_booking_estado_de_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='guest_email',
            field=models.EmailField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='booking',
            name='guest_name',
            field=models.CharField(default='', max_length=40),
        ),
    ]
