# Generated by Django 4.1.5 on 2023-03-11 18:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_booking_guest_email_booking_guest_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='estado_de_pago',
            new_name='pay_status',
        ),
        migrations.AddField(
            model_name='booking',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_method',
            field=models.CharField(choices=[('DEBITO', 'DEBIT_CARD'), ('CREDITO', 'CREDIT_CARD'), ('EFECTIVO', 'CASH'), ('TRANSFERENCIA', 'TRANSFER')], default='', max_length=15),
        ),
        migrations.AddField(
            model_name='booking',
            name='tariff',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
