# Generated by Django 4.1.5 on 2023-03-11 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_rename_estado_de_pago_booking_pay_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='payment_method',
            field=models.CharField(choices=[('DEB', 'DEBITO'), ('CRE', 'CREDITO'), ('EFE', 'EFECTIVO'), ('TRA', 'TRANSFERENCIA')], default='', max_length=15),
        ),
    ]
